[build-system]
requires = ["setuptools", "wheel", "setuptools-git-versioning"]
build-backend = "setuptools.build_meta"

[project]
name = "phantom-wiki"
description = "On-Demand Datasets for Reasoning and Retrieval Evaluation"
dynamic = ["version"]
authors = [
    {name="Albert Gong", email="ag2435@cornell.edu"},
    {name="Chao Wan", email="cw862@cornell.edu"},
    {name="Kamilė Stankevičiūtė", email="ks2448@cornell.edu"},
    {name="Anmol Kabra", email="anmol@cs.cornell.edu"},
    {name="Raphael Thesmar", email="rft38@cornell.edu"},
    {name="Johann Lee", email="jcl354@cornell.edu"},
    {name="JT Klenke", email="jtk96@cornell.edu"},
    {name="Carla Gomes", email="gomes@cs.cornell.edu"},
    {name="Kilian Weinberger", email="kilian@cornell.edu"},
]


readme = "README.md"
requires-python = ">=3.12"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "fastapi>=0.115.0",
    "matplotlib>=3.10.0",
    "networkx",
    "nltk>=3.9.1",
    "numpy>=1.26.4",
    "pandas>=2.2.2",
    "pydot>=1.4.2",
    "pyswip>=0.3.2",
    "sqlalchemy>=2.0.0",
    "tabulate",
    "termcolor",
    "tqdm",
]

[project.optional-dependencies]
dev = [
    "pre-commit",
    "black",
]
tests = [
    "pytest",
    "pytest-cov",
    "httpx",
    "rootutils",
]
docs = [
    "mkdocs==1.6.0",
    "mkdocs-material==9.5.31",
    "mkdocstrings[python,shell]==0.25.2",
    "mkdocs-gen-files==0.5.0",
    "mkdocs-literate-nav==0.6.1",
    "mkdocs-section-index==0.3.9",
    "mkdocs-git-authors-plugin==0.9.0",
    "mkdocs-git-revision-date-localized-plugin==1.2.6"
]
mcp = [
    "mcp>=1.0.0",
]
eval = [
    "anthropic",
    "datasets>=3.1.0",
    "faiss-cpu>=1.9.0.post1",
    "google-generativeai",
    "langchain>=0.3.14",
    "langchain-community",
    "langchain-together",
    "openai",
    "scipy",
    "tiktoken",
    "together",
    "transformers>=4.51.0",
    "bm25s[full]",
    "vllm>=0.8.5",
    "flashrag-dev"
]

[project.scripts]
phantom-wiki-generate = "phantom_wiki.__main__:main"
pw-generate = "phantom_wiki.__main__:main"
phantom-wiki-mcp-server = "phantom_wiki.mcp_server:main"

[project.urls]
Homepage = "https://github.com/kilian-group/phantom-wiki"
Issues = "https://github.com/kilian-group/phantom-wiki/issues"
Repository = "https://github.com/kilian-group/phantom-wiki.git"

[tool.setuptools-git-versioning]
enabled = true

[tool.autoflake]
ignore-init-module-imports = true
